Flexible ab dates
DFE-Digital/prepare-academy-transfers pull request #547
Opened 2023-05-02 15:33 UTC by dneed-nimble

2023-05-02 15:36 UTC, chrisdexnimble requested changes
Think there's a missing } in advisory-board-date.cy.js

2023-05-02 15:36 UTC, chrisdexnimble commented on end-to-end-tests/cypress/e2e/error-messages/advisory-board-date.cy.js
> +            expect(href).includes('/transfer-dates');
I think this is missing a closing }

2023-05-02 15:36 UTC, dneed-nimble commented on end-to-end-tests/cypress/e2e/error-messages/advisory-board-date.cy.js
> +            expect(href).includes('/transfer-dates');
Ah good spot!

2023-05-02 15:42 UTC, chrisdexnimble approved these changes

2023-05-02 17:13 UTC, rdogra-nimble commented on end-to-end-tests/cypress/e2e/error-messages/advisory-board-date.cy.js
> +        cy.url().then(href => {
it could be cy.url().should('include', '/transfer-dates')
however if this works fine by me :)

2023-05-02 17:13 UTC, rdogra-nimble approved these changes

2023-05-03 09:17 UTC, rdogra-nimble approved these changes

2023-05-03 09:18 UTC, merged